{% set name = "gaspium" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gaspium-{{ version }}.tar.gz
  sha256: 4b9e171e997c3af63d5cb552bb61504e2516d9ef02be1e985b22d9a3c21bdd64

build:
  entry_points:
    - gaspium = gaspium.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - viewable
    - viewstack

test:
  imports:
    - gaspium
  commands:
    - pip check
    - gaspium --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/gaspium
  summary: Framework to build Python apps with the GASP metaphor
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
